name  = "worker1"
main  = "dist/index.js"
route = "clickjim.com/*"
workers_dev = true
compatibility_date = "2026-01-09"
# other configuration optionsâ€¦

[build]
command = "npm install && npm run build"